from enum import Enum

class Intent(str, Enum):
    GREETING = "GREETING"
    ASK_RECOMMENDATION = "ASK_RECOMMENDATION"
    ASK_CAR_INFO = "ASK_CAR_INFO"
    FILTER_BY_PRICE = "FILTER_BY_PRICE"
    FILTER_BY_BRAND = "FILTER_BY_BRAND"
    COMPARE_CARS = "COMPARE_CARS"
    CONFIRM_SELECTION = "CONFIRM_SELECTION"
    ASK_POLICY = "ASK_POLICY"
    GOODBYE = "GOODBYE"
    UNKNOWN = "UNKNOWN"
